version: '3.8'

services:
  web:
    build: ./
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    # Открываем порт 8000 наружу
    expose:
      - 8000
    # Подключаем статические файлы
    volumes:
      - static_volume:/home/app/web/static
    env_file:
      - ./.env.prod
  nginx:
    build: ./nginx
    # Подключаем статические файлы
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume: